src/Entity/OffreStage.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass="App\Repository\OffreStageRepository")
 */
class OffreStage
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200, nullable=true)
     */
    private $Description;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank(message = "Veuillez renseigner un nom")
     * @Assert\Length(
     * min = 5,
     * minMessage = "Le nom du stage doit comporter au moins 5 caractères"
     * )
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=100)
     * @Assert\NotBlank(message = "Veuillez renseigner une adresse email")
     */
    private $Mail;

    /**
     * @ORM\Column(type="string", length=30, nullable=true)
     */
    private $Tel;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Formation", mappedBy="stage")
     */
    private $formations;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Entreprise", inversedBy="stages")
     * @ORM\JoinColumn(nullable=false)
     */
    private $entreprise;

    public function __construct()
    {
        $this->formations = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function __tostring(){
        return $this->getNom();
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }

    public function setDescription(?string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function getMail(): ?string
    {
        return $this->Mail;
    }

    public function setMail(string $Mail): self
    {
        $this->Mail = $Mail;

        return $this;
    }

    public function getTel(): ?string
    {
        return $this->Tel;
    }

    public function setTel(?string $Tel): self
    {
        $this->Tel = $Tel;

        return $this;
    }

    /**
     * @return Collection|Formation[]
     */
    public function getFormations(): Collection
    {
        return $this->formations;
    }

    public function addFormation(Formation $formation): self
    {
        if (!$this->formations->contains($formation)) {
            $this->formations[] = $formation;
            $formation->addStage($this);
        }

        return $this;
    }

    public function removeFormation(Formation $formation): self
    {
        if ($this->formations->contains($formation)) {
            $this->formations->removeElement($formation);
            $formation->removeStage($this);
        }

        return $this;
    }

    public function getEntreprise(): ?Entreprise
    {
        return $this->entreprise;
    }

    public function setEntreprise(?Entreprise $entreprise): self
    {
        $this->entreprise = $entreprise;

        return $this;
    }
}

src/Controller/ProstagesController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Entreprise;
use App\Entity\OffreStage;
use App\Entity\Formation;
use App\Form\EntrepriseType;
use App\Form\OffreStageType;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Form\Extension\Core\Type\UrlType;
use Symfony\Component\Form\Extension\Core\Type\EmailType;
use Symfony\Component\Form\Extension\Core\Type\TelType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Doctrine\Common\Persistence\ObjectManager;

class ProstagesController extends AbstractController
{
    /**
     * @Route("/prostages", name="prostagesAccueil")
     */
    public function index()
    {
        return $this->render('prostages/index.html.twig', [
            'controller_name' => 'ProstagesController',
        ]);
    }
    /**
     * @Route("/prostages/entreprises", name="prostagesEntreprises")
     */
    public function affEntreprises()
    {
        $listeEntreprises = $this->getDoctrine()->getRepository(Entreprise::class)->findAll();

        return $this->render('prostages/entreprises.html.twig', ['controller_name' => 'ProstagesController', 
                                                                 'listeEntreprises' => $listeEntreprises]);
    }
    /**
     * @Route("/prostages/formations", name="prostagesFormations")
     */
    public function affFormations()
    {
        $listeFormations = $this->getDoctrine()->getRepository(Formation::class)->findByNomASC();

        return $this->render('prostages/formations.html.twig', ['controller_name' => 'ProstagesController',
                                                                'listeFormations' => $listeFormations]);
    }
    /**
     * @Route("/prostages/stages/{idEtu}", name="prostagesStages")
     */
    public function affStages($idEtu)
    {
        //Récupération des stages et des formations
        $listeStages = $this->getDoctrine()->getRepository(OffreStage::class)->findAll();
        $listeFormations = $this->getDoctrine()->getRepository(Formation::class)->findAll();

        //Envoi des informations à la vue
        return $this->render('prostages/stages.html.twig', ['controller_name' => 'ProstagesController', 'idEtu' => $idEtu,
                                                            'listeStages' => $listeStages,
                                                            'listeFormations' => $listeFormations]);
    }
    /**
     * @Route("/prostages/entreprises/ajouter", name="prostagesEntreprisesForm")
     */
    public function affFormEntreprises(Request $requeteHttp, ObjectManager $manager)
    {
        // Création d'une entreprise vierge
        $entreprise = new Entreprise();

        // Création d'un formulaire pour saisir les détails d'une entreprise
        $formulaireEntreprise = $this -> createForm(EntrepriseType::class, $entreprise);
        // Les stages ne seront saisis qu'après la saisie des détails de l'entreprise

        $formulaireEntreprise -> handleRequest($requeteHttp);

        // Vérification des saisies, soumission du formulaire
        if($formulaireEntreprise -> isSubmitted()  && $formulaireEntreprise -> isValid()){

            // Enregistrement de l'entreprise en BD
            $manager->persist($entreprise);
            $manager->flush();

            // Redirection de l'utilisateur vers la liste des entreprises
            return $this -> redirectToRoute('prostagesEntreprises');
        }

        // Générer la vue représentant le formulaire
        $vueFormEntreprise = $formulaireEntreprise -> createView();

        // Afficher le page d'ajout d'une entreprise
        return $this -> render('prostages/formAjoutEntreprise.html.twig',
                               ['vueFormEntreprise' => $vueFormEntreprise]);
    }
    /**
     * @Route("/prostages/stage-ajout", name="prostagesStageForm")
     */
    public function affFormStages(Request $requeteHttp, ObjectManager $manager){
        $stage = new OffreStage();
        $formStage = $this -> createForm(OffreStageType::class, $stage);
        $formStage -> handleRequest($requeteHttp);
        if($formStage -> isSubmitted() && $formStage -> isValid()){
            $manager -> persist($stage);
            $manager -> flush();
            return $this -> redirectToRoute('prostagesStages');
        }
        $vueFormStage = $formStage -> createView();
        return $this -> render('prostages/formAjoutStage.html.twig',
                                ['vueFormStage' => $vueFormStage]);
    }
}

templates/prostages/entreprises.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page des entreprises{% endblock %}

{% block body %}

<style>
	.col-container{
		display: flex;
		width: 100%;
	}

	.col {
		flex: 1;
		padding: 16px;
	}
</style>

<h3>Liste des entreprises proposant un stage</h3>

<div class="table">


	<div class="row">
		{% for entreprise in listeEntreprises %}
		<div class="col-md-4">
			<div class="jumbotron">
				<h2>
					{{ entreprise.nom }}
				</h2>
				<h4>
					{{ entreprise.type }}
				</h4>
				<p>
					{{ entreprise.site }}
				</p>
				<p>
					{{ entreprise.adresse }}
				</p>
				<h4>
					{{ entreprise.tel }}
				</h4>
			</div>
		</div>
		{% endfor %}
	</div>

</div>

<h4><a href='/prostages/entreprises/ajouter'>Ajouter une entreprise</a><br></h4>
<h4><a href='/prostages/'>Revenir à l'accueil</a><br></h4>
<h4><a href="{{ path('app_logout') }}">Se déconnecter</a></h4>
{% endblock %}

templates/prostages/formAjoutEntreprise.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'ajout d'entreprises{% endblock %}

{% block body %}

<h3>Formulaire d'ajout d'entreprises</h3>
{% form_theme vueFormEntreprise 'foundation_5_layout.html.twig' %}
{{ form_start (vueFormEntreprise) }}
<div>
    {{ form_label (vueFormEntreprise.nom) }}
    {{ form_errors (vueFormEntreprise.nom) }}
    {{ form_widget (vueFormEntreprise.nom) }}
</div>
<div>
        {{ form_label (vueFormEntreprise.type) }}
        {{ form_errors (vueFormEntreprise.type) }}
        {{ form_widget (vueFormEntreprise.type) }}
</div>
<div>
        {{ form_label (vueFormEntreprise.site) }}
        {{ form_errors (vueFormEntreprise.site) }}
        {{ form_widget (vueFormEntreprise.site) }}
</div>
<div>
        {{ form_label (vueFormEntreprise.adresse) }}
        {{ form_errors (vueFormEntreprise.adresse) }}
        {{ form_widget (vueFormEntreprise.adresse) }}
</div>
<div>
        {{ form_label (vueFormEntreprise.tel) }}
        {{ form_errors (vueFormEntreprise.tel) }}
        {{ form_widget (vueFormEntreprise.tel) }}
</div>
{{ form_end (vueFormEntreprise) }}

<h4><a href='/prostages/entreprises'>Revenir à la liste des entreprises</a><br></h4>
<h4><a href='/prostages'>Revenir à l'accueil</a><br></h4>
<h4><a href="{{ path('app_logout') }}">Se déconnecter</a></h4>
{% endblock %}

templates/prostages/formAjoutStage.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page d'ajout de stage{% endblock %}

{% block body %}

<h3>Formulaire d'ajout de stage</h3>
{% form_theme vueFormStage 'foundation_5_layout.html.twig' %}
{{ form_start (vueFormStage) }}
<div>
    {{ form_label (vueFormStage.entreprise) }}
    {{ form_errors (vueFormStage.entreprise) }}
    {{ form_widget (vueFormStage.entreprise) }}
</div>
<div>
        {{ form_label (vueFormStage.Nom) }}
        {{ form_errors (vueFormStage.Nom) }}
        {{ form_widget (vueFormStage.Nom) }}
</div>
<div>
        {{ form_label (vueFormStage.Description) }}
        {{ form_errors (vueFormStage.Description) }}
        {{ form_widget (vueFormStage.Description) }}
</div>
<div>
        {{ form_label (vueFormStage.Mail) }}
        {{ form_errors (vueFormStage.Mail) }}
        {{ form_widget (vueFormStage.Mail) }}
</div>
<div>
        {{ form_label (vueFormStage.Tel) }}
        {{ form_errors (vueFormStage.Tel) }}
        {{ form_widget (vueFormStage.Tel) }}
</div>
<div>
        {{ form_label (vueFormStage.formations) }}
        {{ form_errors (vueFormStage.formations) }}
        {{ form_widget (vueFormStage.formations) }}
</div>
{{ form_end (vueFormStage) }}

<h4><a href='/prostages/stages/0'>Revenir à la liste des stages</a><br></h4>
<h4><a href='/prostages'>Revenir à l'accueil</a><br></h4>
<h4><a href="{{ path('app_logout') }}">Se déconnecter</a></h4>
{% endblock %}

templates/prostages/formations.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page des formations{% endblock %}

{% block body %}

<style>
    table,
    th,
    tr {
        border: 4px solid black;
    }
</style>

<h3>Liste des formations disponibles</h3>

<table>
    <tr>
        <th><h3>Nom de la formation</h3></th>
        <th><h3>Diplôme concerné</h3></th>
    </tr>

    {% for formation in listeFormations %}
    <tr>
        <th>
            <h3>
                {{ formation.nom }}
            </h3>
        </th>
        <th>
            <h4>
                {{ formation.diplome }}
            </h4>
        </th>
    </tr>
    {% endfor %}
</table>

<h4><a href='/prostages'>Revenir à l'accueil</a><br></h4>
<h4><a href="{{ path('app_logout') }}">Se déconnecter</a></h4>

{% endblock %}

templates/prostages/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProstagesController!{% endblock %}

{% block body %}
<style>
    .example-wrapper {
        margin: 1em auto;
        max-width: 800px;
        width: 95%;
        font: 18px/1.5 sans-serif;
    }

    .example-wrapper code {
        background: #F5F5F5;
        padding: 2px 6px;
    }
</style>

<h3>Bienvenue sur la page d'accueil de Prostages</h3>
<br>
<p>
    <center>
        <h2>Menu de base</h2>
    </center>
    <h4><a href='formation'>Formations disponibles</a><br></h4>
    <h4><a href='prostages/stages/0'>Stages disponibles</a><br></h4>
    <h4><a href='prostages/entreprises'>Entreprises disponibles</a><br></h4>
</p>

<!--Faire un <img src="nomImg">. Les images se trouvent dans le dossier public-->
<h4><a href="{{ path('app_logout') }}">Se déconnecter</a></h4>

{% endblock %}

templates/prostages/selectStagesEtu.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page des stages{% endblock %}

{% block body %}
<form action="stages/{idEtu}" method="POST">
    <h1>Veuillez saisir un identifiant d'étudiant : </h1>
    <input type="text" name="numEtuStages"><br><br>
    <input type="submit" value="Chercher des stages">
</form>

{% endblock %}

templates/prostages/stages.html.twig
{% extends 'base.html.twig' %}

{% block title %}Page des stages{% endblock %}

{% block body %}

{% if idEtu == 0 %}
	<h3>Liste des stages disponibles</h3>
{% else %}
	<h3>Liste des stages de l'étudiant {{idEtu}}</h3>
{% endif %}
<h4><a href="/prostages/stage-ajout">Ajouter un stage</a></h4>
<h4><a href='/prostages'>Revenir à l'accueil</a><br></h4>

<div class="table">


	<div class="row">
		{% for stage in listeStages %}
		<div class="col-md-4">
			<div class="jumbotron">
				<h2>
					{{ stage.Nom }}
                </h2>
				<p>
					{{ stage.Description }}
				</p>
				<h4>
                    Entreprise : {{ stage.entreprise.nom }}
                </h4>
                <h4>
                    Contactez-nous : {{ stage.Mail }}
                </h4>
                <h4>
                    Téléphone : {{ stage.Tel }}
                </h4>
			</div>
		</div>
		{% endfor %}
	</div>

</div>
<h3><a href="{{ path('app_logout') }}">Se déconnecter</a></h3>
{% endblock %}